version: "3.7"

services:
  mc:
    image: itzg/minecraft-server
    restart: always
    ports:
      - "25565:25565"
    environment:
      #CF_API_KEY: $$2a$$10$$3rjBrlcmwnywR7KlEAqV0.Wunt4IWADYq8RSojWeYdx97zDGw6qs6
      EULA: "TRUE"
      MEMORY: "15G"
      TYPE: "FORGE"
      VERSION: "1.20.1"
      MOTD: "Muerte al WARDENNNNNNN!!!"
      DIFFICULTY: "normal"
      ICON: "https://i.imgur.com/Z5MBi7z.jpeg"
      OVERRIDE_ICON: "TRUE"
      MAX_WORLD_SIZE: 29999984
      MODE: "survival"
      ONLINE_MODE: "TRUE"
    volumes:
      - ./data:/data
      - ./downloads/mods:/data/mods

