version: "3.7"

services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      TYPE: FORGE
      #CF_API_KEY: $$2a$$10$$3rjBrlcmwnywR7KlEAqV0.Wunt4IWADYq8RSojWeYdx97zDGw6qs6
      EULA: "TRUE"
      MEMORY: "4G"
      VERSION: "1.21"
      MOTD: "¡Bienvenido a mi servidor de Minecraft ratas cloud!"
      DIFFICULTY: "normal"
      ICON: "/data/ICONO.webp"
      OVERRIDE_ICON: "TRUE"
      MAX_WORLD_SIZE: 5000
      MODE: "survival"
      ONLINE_MODE: "FALSE"
    volumes:
      - ./data:/data
      - ./downloads/mods:/data/mods

